on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: release

      - name: Fetch all tags
        run: |
          git fetch --tags --force
          git tag -l
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9.18'
      
      - name: Install dependencies
        run: pip install -r requirements.txt.ci
      
      - name: Release the package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_PUBLISHER }}
        run: |
            git config --global user.email "semantic-release@github-actions"
            git config --global user.name "semantic-release (via Github Actions)"
            semantic-release publish
            git checkout release && git pull origin release && git push origin release:master